export { ReactComponent as ArrowRight } from "./arrowRight.svg"
export { ReactComponent as Cart } from "./cart.svg"
export { ReactComponent as Close } from "./close.svg"
export { ReactComponent as Hamburger } from "./hamburger.svg"
export { ReactComponent as Search } from "./search.svg"
export { ReactComponent as WishList } from "./wishlist.svg"
export { ReactComponent as Account } from "./account.svg"
